/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-06-04 09:57:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editMatiere_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <script>\r\n");
      out.write("    function notify(msg, type = \"info\") {\r\n");
      out.write("        let notif = document.createElement(\"div\");\r\n");
      out.write("        notif.className = \"notif \" + type;\r\n");
      out.write("        notif.innerText = msg;\r\n");
      out.write("        document.body.appendChild(notif);\r\n");
      out.write("        setTimeout(() => notif.remove(), 3000);\r\n");
      out.write("    }\r\n");
      out.write("    function confirmAction(msg, url) {\r\n");
      out.write("        if (confirm(msg)) {\r\n");
      out.write("            window.location = url;\r\n");
      out.write("        }\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("    <style>\r\n");
      out.write("    .notif {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 30px; right: 30px;\r\n");
      out.write("        background: #2e7dff;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        padding: 16px 32px;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        font-size: 1.1em;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("        box-shadow: 0 2px 8px rgba(0,0,0,0.15);\r\n");
      out.write("        opacity: 0.95;\r\n");
      out.write("        animation: fadein 0.5s;\r\n");
      out.write("    }\r\n");
      out.write("    .notif.error { background: #e74c3c; }\r\n");
      out.write("    .notif.success { background: #27ae60; }\r\n");
      out.write("    @keyframes fadein { from { opacity: 0; top: 0; } to { opacity: 0.95; top: 30px; } }\r\n");
      out.write("    </style>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Éditer Matière</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <h2>MonApp</h2>\r\n");
      out.write("        <a href=\"home.jsp\">🏠 Accueil</a>\r\n");
      out.write("        <a href=\"matiere\">📚 Voir les matières</a>\r\n");
      out.write("        <a href=\"compte\">👤 Voir les comptes</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h1>Éditer une Matière</h1>\r\n");
      out.write("            <a href=\"matiere\" class=\"btn\">Retour</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content-box\">\r\n");
      out.write("            <form method=\"post\" action=\"matiere\">\r\n");
      out.write("                <input type=\"hidden\" name=\"id\" value=\"");
      out.print( ((model.Matiere)request.getAttribute("matiere")).getId() );
      out.write("\">\r\n");
      out.write("                <input type=\"text\" name=\"nom\" placeholder=\"Nom de la matière\" required value=\"");
      out.print( ((model.Matiere)request.getAttribute("matiere")).getNom() );
      out.write("\">\r\n");
      out.write("                <input type=\"number\" name=\"nb_heures\" placeholder=\"Nombre d'heures\" required value=\"");
      out.print( ((model.Matiere)request.getAttribute("matiere")).getNbHeures() );
      out.write("\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn\">Enregistrer</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
