/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.105
 * Generated at: 2025-06-04 09:58:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.dao.CompteDAO;
import model.Compte;

public final class profil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("model.Compte");
    _jspx_imports_classes.add("model.dao.CompteDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- filepath: c:\\Users\\diego\\OneDrive\\BACHELOR\\Cours\\Devoir MmeSans\\programmation objet\\monapp-jsp\\src\\main\\webapp\\profil.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String login = (String) session.getAttribute("user");
    String role = (String) session.getAttribute("role");
    Compte compte = null;
    if (login != null) {
        compte = new model.dao.CompteDAO().getByLogin(login);
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Mon Profil</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("    .profil-container {\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        margin: 60px auto;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        box-shadow: 0 2px 16px rgba(0,0,0,0.10);\r\n");
      out.write("        padding: 32px 28px;\r\n");
      out.write("    }\r\n");
      out.write("    .profil-info {\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .profil-info span {\r\n");
      out.write("        display: block;\r\n");
      out.write("        font-size: 1.1em;\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    .profil-btn {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin: 0 auto 18px auto;\r\n");
      out.write("        padding: 10px 24px;\r\n");
      out.write("        background: #2e7dff;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        font-size: 1em;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("    .profil-btn:hover {\r\n");
      out.write("        background: #1b4fa0;\r\n");
      out.write("    }\r\n");
      out.write("    .profil-form {\r\n");
      out.write("        display: none;\r\n");
      out.write("        margin-top: 18px;\r\n");
      out.write("    }\r\n");
      out.write("    .profil-form input {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin-bottom: 14px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        border: 1px solid #bbb;\r\n");
      out.write("        font-size: 1em;\r\n");
      out.write("    }\r\n");
      out.write("    .profil-form button {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        background: #27ae60;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        font-size: 1.1em;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("    .profil-form button:hover {\r\n");
      out.write("        background: #219150;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("    function showEditForm() {\r\n");
      out.write("        document.getElementById(\"profil-form\").style.display = \"block\";\r\n");
      out.write("        document.getElementById(\"edit-btn\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <h2>MonApp</h2>\r\n");
      out.write("        <a href=\"profil.jsp\">🙍‍♂️ Profil</a>\r\n");
      out.write("        <a href=\"home.jsp\">🏠 Accueil</a>\r\n");
      out.write("        <a href=\"matiere\">📚 Voir les matières</a>\r\n");
      out.write("        <a href=\"compte\">👤 Voir les comptes</a>\r\n");
      out.write("        <a href=\"logout\" class=\"btn\">Déconnexion</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h1>Mon Profil</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"profil-container\">\r\n");
      out.write("        ");
 if (login != null && compte != null) { 
      out.write("\r\n");
      out.write("            <div class=\"profil-info\">\r\n");
      out.write("                <span><strong>Nom d'utilisateur :</strong> ");
      out.print( compte.getLogin() );
      out.write("</span>\r\n");
      out.write("                <span><strong>Rôle :</strong> ");
      out.print( compte.getRole() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button id=\"edit-btn\" class=\"profil-btn\" onclick=\"showEditForm()\">Modifier mon profil</button>\r\n");
      out.write("            <form id=\"profil-form\" class=\"profil-form\" method=\"post\" action=\"profil\">\r\n");
      out.write("                <input type=\"text\" name=\"login\" value=\"");
      out.print( compte.getLogin() );
      out.write("\" required placeholder=\"Nom d'utilisateur\">\r\n");
      out.write("                <input type=\"password\" name=\"password\" placeholder=\"Nouveau mot de passe (laisser vide pour ne pas changer)\">\r\n");
      out.write("                <button type=\"submit\">Enregistrer les modifications</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <p>Vous devez être connecté pour voir cette page.</p>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

            String notif = request.getParameter("notif");
            if ("success_edit".equals(notif)) {
        
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            notify(\"Profil modifié avec succès\", \"success\");\r\n");
      out.write("        </script>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
